# Generated by Django 3.2.3 on 2021-05-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('sname', models.CharField(max_length=30)),
                ('srno', models.IntegerField(primary_key=True, serialize=False)),
                ('mark1', models.IntegerField()),
                ('mark2', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('rno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
